import Foundation
import RunnerCore

/// Renders the two configuration documents `setup` writes.
///
/// Written as text rather than encoded from `RunnerConfiguration`, deliberately: the file an
/// operator opens next is more valuable with comments explaining why each number is what it is
/// than with an exhaustive dump of every defaulted key. `docs/examples/headless-mac-mini.yaml` is
/// the house style this follows. `SetupPlanTests` proves both documents load and validate, so the
/// hand-written form cannot drift from what `ConfigLoader` accepts.
enum SetupYAML {
  struct Context: Sendable {
    var answers: SetupAnswers
    var facts: SetupHostFacts
    var stateDir: String
    var profiles: [PlannedProfile]
    var managed: [ManagedImageSourceConfig]
    /// The promoted macOS image's exact virtual size. `nil` until a provisioning run has produced
    /// one, which is what keeps the macOS profile commented out.
    var macOSDiskBytes: UInt64?

    init(
      answers: SetupAnswers, facts: SetupHostFacts, stateDir: String,
      profiles: [PlannedProfile], managed: [ManagedImageSourceConfig],
      macOSDiskBytes: UInt64? = nil
    ) {
      self.answers = answers
      self.facts = facts
      self.stateDir = stateDir
      self.profiles = profiles
      self.managed = managed
      self.macOSDiskBytes = macOSDiskBytes
    }
  }

  static func render(_ context: Context, includeProfiles: Bool) -> String {
    var sections = [
      header(context, includeProfiles: includeProfiles),
      hostBlock(context),
      githubBlock(context),
      imagesBlock(context),
      imageUpdatesBlock(),
    ]
    if includeProfiles {
      sections.append(profilesBlock(context))
    } else {
      sections.append(deferredProfilesNote())
    }
    return sections.joined(separator: "\n\n") + "\n"
  }

  // MARK: - Header

  private static func header(_ context: Context, includeProfiles: Bool) -> String {
    let facts = context.facts
    var lines = [
      "# RunnerVM — generated by `runnerctl setup`.",
      "#",
      "# Host: \(facts.model), \(facts.cpuCount) logical CPUs, "
        + "\(ByteSize(bytes: facts.memoryBytes)) RAM.",
      "# Edit freely, then apply with:  sudo runnerctl config apply --file \(context.stateDir)/config.yaml",
    ]
    if !includeProfiles {
      lines.append("#")
      lines.append("# This is the bootstrap document: no profiles yet, because a profile whose")
      lines.append("# image is not in the store would stall the daemon's first start on a pull.")
      lines.append("# `setup` rewrites it with the profiles once the images are present.")
    }
    lines.append("version: \(RunnerConfiguration.currentVersion)")
    return lines.joined(separator: "\n")
  }

  // MARK: - host

  private static func hostBlock(_ context: Context) -> String {
    let reserve = SetupDefaults.reserve
    let facts = context.facts
    return ([
      "host:",
      "  # Headroom never handed to guests: macOS itself, the daemon, and its logs.",
      "  reserve:",
      commented("    cpu: \(reserve.cpu)", "of \(facts.cpuCount) logical CPUs"),
      commented(
        "    memory: \(bytes(reserve.memoryBytes))", "of \(ByteSize(bytes: facts.memoryBytes))"),
      commented("    disk: \(bytes(reserve.diskBytes))", "absolute free-space floor"),
      "  # No absolute VM ceiling: capacity is whatever the budget above allows. Set an integer",
      "  # here to cap the host below that.",
      "  maxVMs: auto",
    ] as [String]).joined(separator: "\n")
  }

  // MARK: - github

  private static func githubBlock(_ context: Context) -> String {
    let scope = context.answers.scope
    var lines = [
      "github:",
      "  demand: scaleSet",
      "  auth:",
      "    provider: pat",
      "    # An owner-only file under the state directory, not the login keychain: a headless",
      "    # LaunchDaemon has no login session to unlock one.",
      "    source: file",
      "  scopes:",
      "    - name: \(scope.configName)",
      "      type: \(scope.kind.rawValue)",
      "      owner: \(scope.owner)",
    ]
    if let repository = scope.repository {
      lines.append("      repository: \(repository)")
    } else {
      lines.append("      runnerGroup: \(context.answers.runnerGroup)")
    }
    return lines.joined(separator: "\n")
  }

  // MARK: - images

  private static func imagesBlock(_ context: Context) -> String {
    var lines = [
      "images:",
      "  # Pull every profile's image when the configuration is applied, so the first job after a",
      "  # config change is not waiting on a download that looks like a runner failure.",
      "  prefetch: true",
      "  updates:",
      "    enabled: true",
      "    interval: 6h            # at least 15m",
      "    jitter: 30m             # so a fleet does not check in lockstep",
      "    keepPrevious: 1         # superseded digests kept; the only deletion trigger",
      "    smokeTest: true         # qualify a candidate before it is promoted",
    ]
    guard !context.managed.isEmpty else { return lines.joined(separator: "\n") }
    lines.append("  # Sources RunnerVM keeps current on this host's own behalf. A macos-tart source")
    lines.append("  # is never runnable as pulled: it is provisioned locally, then promoted to the")
    lines.append("  # alias below, which the macOS profile names as its image.")
    lines.append("  managed:")
    for entry in context.managed {
      lines.append("    - name: \(entry.name)")
      lines.append("      kind: macos-tart")
      lines.append("      source: \(entry.source)")
      lines.append("      autoUpdate: \(entry.autoUpdate)")
      if let resources = entry.resources {
        lines.append("      resources:              # the provisioning VM's sizing")
        lines.append("        cpu: \(resources.cpuCount)")
        lines.append("        memory: \(bytes(resources.memoryBytes))")
      }
    }
    return lines.joined(separator: "\n")
  }

  private static func imageUpdatesBlock() -> String {
    """
    imageUpdates:
      # Refuse to boot an image whose baked-in actions/runner has fallen past GitHub's 30-day
      # update window, rather than only warning about it.
      denyTooOldRunner: true
    """
  }

  // MARK: - profiles

  private static func profilesBlock(_ context: Context) -> String {
    // A deferred macOS profile becomes a live one the moment its image's size is known: that
    // number is the only thing that was missing.
    let diskBytes = context.macOSDiskBytes
    let active = context.profiles.filter { !$0.deferred || diskBytes != nil }
    var lines: [String] = []
    if active.isEmpty {
      lines.append("# No runner profiles: no environment was selected at setup time.")
      lines.append("# profiles: []")
    } else {
      lines.append("profiles:")
      for profile in active {
        if profile.guestOS == .macos, let diskBytes {
          lines.append(contentsOf: macOSProfileLines(profile, context: context, diskBytes: diskBytes))
        } else {
          lines.append(contentsOf: linuxProfileLines(profile, context: context))
        }
      }
    }
    guard diskBytes == nil else { return lines.joined(separator: "\n") }
    for profile in context.profiles where profile.deferred {
      lines.append("")
      lines.append(contentsOf: macOSProfileBlock(profile, context: context))
    }
    return lines.joined(separator: "\n")
  }

  private static func linuxProfileLines(
    _ profile: PlannedProfile, context: Context
  ) -> [String] {
    [
      commented("  - name: \(profile.name)", "also the runs-on label and the scale-set name"),
      "    scope: \(context.answers.scope.configName)",
      "    image: \(profile.image)",
      "    os: \(profile.guestOS.rawValue)",
      commented("    lifecycle: ephemeral", "one job per VM, then destroyed"),
      "    resources:",
      "      cpu: \(profile.resources.cpuCount)",
      "      memory: \(bytes(profile.resources.memoryBytes))",
      commented(
        "      disk: \(bytes(profile.resources.diskBytes))",
        "must be >= the image's disk layer"),
      "    limits:",
      "      maxInstances: \(profile.maxInstances)",
    ]
  }

  /// The live macOS profile, written only after a provisioning run has promoted an image.
  ///
  /// `disk` is the promoted image's exact virtual size in bytes, not a rounded unit: a macOS guest
  /// cannot resize its APFS container, so a profile whose `disk` differs from the image's by a
  /// single byte is a profile no instance can boot. It is spelled with the `B` suffix so it stays
  /// a string YAML resolves the same way `16GiB` is resolved.
  static func macOSProfileLines(
    _ profile: PlannedProfile, context: Context, diskBytes: UInt64
  ) -> [String] {
    [
      commented("  - name: \(profile.name)", "also the runs-on label and the scale-set name"),
      "    scope: \(context.answers.scope.configName)",
      commented("    image: \(profile.image)", "the images.managed[] alias, above"),
      "    os: macos",
      commented("    lifecycle: ephemeral", "one job per VM, then destroyed"),
      "    resources:",
      "      cpu: \(profile.resources.cpuCount)",
      "      memory: \(bytes(profile.resources.memoryBytes))",
      commented(
        "      disk: \(bytes(diskBytes))", "the promoted image's exact virtual size"),
      "    limits:",
      "      maxInstances: \(profile.maxInstances)",
    ]
  }

  /// The macOS profile as it is emitted *before* an image exists: commented out.
  ///
  /// Two reasons, both hard: the managed image does not exist until a local provisioning run has
  /// produced and promoted it, and a macOS guest cannot resize its APFS container, so
  /// `resources.disk` must equal the produced image's exact virtual size — a number nobody has
  /// before that run. An active profile pointing at a missing alias would fail every job on it.
  ///
  /// `setup --macos` normally never leaves this in place: it runs the provisioning itself and
  /// re-renders the document through `macOSProfileLines`. This block is what a host is left with
  /// when that run failed or was not asked for.
  static func macOSProfileBlock(_ profile: PlannedProfile, context: Context) -> [String] {
    [
      "# macOS profile — activate after the managed image has been provisioned and promoted.",
      "#",
      "# Provision it, which builds, qualifies and promotes a local image:",
      "#   sudo runnerctl image update run --managed \(context.answers.managedImageName)",
      "# then uncomment this block, set `disk` to the image's exact virtual size (macOS guests",
      "# cannot resize their APFS container, so the profile must match the image), and apply:",
      "#   sudo runnerctl config apply --file \(context.stateDir)/config.yaml",
      "#",
      "#   - name: \(profile.name)",
      "#     scope: \(context.answers.scope.configName)",
      "#     image: \(profile.image)",
      "#     os: macos",
      "#     lifecycle: ephemeral",
      "#     resources:",
      "#       cpu: \(profile.resources.cpuCount)",
      "#       memory: \(bytes(profile.resources.memoryBytes))",
      "#       disk: 50GB                  # set to the image's exact virtual size after first provision",
      "#     limits:",
      "#       maxInstances: \(profile.maxInstances)",
    ]
  }

  private static func deferredProfilesNote() -> String {
    "# profiles: written by `runnerctl setup` once the images are in the store."
  }

  // MARK: - Formatting

  /// A trailing comment at a fixed column, so the generated document reads as a column of notes
  /// rather than ragged text. Values wider than the column get a single space.
  private static func commented(_ code: String, _ note: String, column: Int = 34) -> String {
    let padding = max(1, column - code.count)
    return code + String(repeating: " ", count: padding) + "# " + note
  }

  /// Exact binary multiples where the value is one, a plain byte count otherwise — never a rounded
  /// "3.5GiB", which would not round-trip through `ByteSize`.
  ///
  /// The fallback carries the `B` suffix on purpose: a bare integer is a YAML *number*, and
  /// `ByteSize` decodes from a string, so `disk: 68719476736` would fail to load while
  /// `disk: 68719476736B` is exactly the same quantity and does.
  private static func bytes(_ value: UInt64) -> String {
    let units: [(String, UInt64)] = [("TiB", 1 << 40), ("GiB", 1 << 30), ("MiB", 1 << 20)]
    for (name, factor) in units where value >= factor && value % factor == 0 {
      return "\(value / factor)\(name)"
    }
    return "\(value)B"
  }
}
